// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnqmVzld1ozO2-pNTNRcxLn5UF9Itue8Q',
    appId: '1:501147131892:web:44ea86662ea078d03ba3a1',
    messagingSenderId: '501147131892',
    projectId: 'chat-app-mahmoud-c518e',
    authDomain: 'chat-app-mahmoud-c518e.firebaseapp.com',
    storageBucket: 'chat-app-mahmoud-c518e.firebasestorage.app',
    measurementId: 'G-XV6CLBDDSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzuow0bMP0fdaIGAkyK72JmGDE5AOa3gY',
    appId: '1:501147131892:android:503d95dbcdce757d3ba3a1',
    messagingSenderId: '501147131892',
    projectId: 'chat-app-mahmoud-c518e',
    storageBucket: 'chat-app-mahmoud-c518e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFAKKO6qyxWjhHMwKIkJMXiZxP8iPc-4c',
    appId: '1:501147131892:ios:8bf2d1669137ed453ba3a1',
    messagingSenderId: '501147131892',
    projectId: 'chat-app-mahmoud-c518e',
    storageBucket: 'chat-app-mahmoud-c518e.firebasestorage.app',
    iosBundleId: 'com.example.chatAppMahmoud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFAKKO6qyxWjhHMwKIkJMXiZxP8iPc-4c',
    appId: '1:501147131892:ios:8bf2d1669137ed453ba3a1',
    messagingSenderId: '501147131892',
    projectId: 'chat-app-mahmoud-c518e',
    storageBucket: 'chat-app-mahmoud-c518e.firebasestorage.app',
    iosBundleId: 'com.example.chatAppMahmoud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnqmVzld1ozO2-pNTNRcxLn5UF9Itue8Q',
    appId: '1:501147131892:web:b3fc775d7eb8ad573ba3a1',
    messagingSenderId: '501147131892',
    projectId: 'chat-app-mahmoud-c518e',
    authDomain: 'chat-app-mahmoud-c518e.firebaseapp.com',
    storageBucket: 'chat-app-mahmoud-c518e.firebasestorage.app',
    measurementId: 'G-2P37L5XGCC',
  );
}
